runtime: nodejs20
service: goat-pen-test
instance_class: F2

handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /.*
    script: auto
    secure: always

env_variables:
  NEXT_PUBLIC_API_URL: ""
